# -*- coding: utf-8 -*-
# :Project:   pglast — DO NOT EDIT: type stubs automatically extracted from sfuncs.py
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017-2026 Lele Gaifax
#

from .. import ast
from ..stream import RawStream

def btrim(node: ast.FuncCall, output: RawStream) -> None: ...

def pg_collation_for(node: ast.FuncCall, output: RawStream) -> None: ...

def extract(node: ast.FuncCall, output: RawStream) -> None: ...

def ltrim(node: ast.FuncCall, output: RawStream) -> None: ...

def normalize(node: ast.FuncCall, output: RawStream) -> None: ...

def overlaps(node: ast.FuncCall, output: RawStream) -> None: ...

def overlay(node: ast.FuncCall, output: RawStream) -> None: ...

def position(node: ast.FuncCall, output: RawStream) -> None: ...

def rtrim(node: ast.FuncCall, output: RawStream) -> None: ...

def substring(node: ast.FuncCall, output: RawStream) -> None: ...

def timezone(node: ast.FuncCall, output: RawStream) -> None: ...

def xmlexists(node: ast.FuncCall, output: RawStream) -> None: ...
