# -*- coding: utf-8 -*-
# :Project:   pglast — bump-my-version configuration
# :Created:   mer 30 ott 2024, 07:49:26
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2024 Lele Gaifax
#

[tool.bumpversion]
current_version = "7.5"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)"
serialize = [
    "{major}.{minor}",
    "{major}.{minor}",
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "setup.py"
search = 'version="{current_version}"'
replace = 'version="{new_version}"'

[[tool.bumpversion.files]]
filename = "pglast/__init__.py"
search = "__version__ = 'v{current_version}'"
replace = "__version__ = 'v{new_version}'"

[[tool.bumpversion.files]]
filename = "docs/conf.py"
search = "release = 'v{current_version}'"
replace = "release = 'v{new_version}'"
