# -*- coding: utf-8 -*-
# :Project:   pglast — DO NOT EDIT: type stubs automatically extracted from cmptype.h @ 18-latest-0-g9ab9951
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017-2026 Lele Gaifax
#

from enum import IntEnum


class CompareType(IntEnum):
    COMPARE_INVALID = ...
    COMPARE_LT = ...
    COMPARE_LE = ...
    COMPARE_EQ = ...
    COMPARE_GE = ...
    COMPARE_GT = ...
    COMPARE_NE = ...
    COMPARE_OVERLAP = ...
    COMPARE_CONTAINED_BY = ...
