# -*- coding: utf-8 -*-
# :Project:   pglast — DO NOT EDIT: type stubs automatically extracted from lockoptions.h @ 18-latest-0-g6ced8d4
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017-2026 Lele Gaifax
#

from enum import IntEnum


class LockClauseStrength(IntEnum):
    LCS_NONE = ...
    LCS_FORKEYSHARE = ...
    LCS_FORSHARE = ...
    LCS_FORNOKEYUPDATE = ...
    LCS_FORUPDATE = ...


class LockTupleMode(IntEnum):
    LockTupleKeyShare = ...
    LockTupleShare = ...
    LockTupleNoKeyExclusive = ...
    LockTupleExclusive = ...


class LockWaitPolicy(IntEnum):
    LockWaitBlock = ...
    LockWaitSkip = ...
    LockWaitError = ...
