# -*- coding: utf-8 -*-
# :Project:   pglast — DO NOT EDIT: type stubs automatically extracted from xml.h @ 18-latest-0-g6ced8d4
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   GNU General Public License version 3 or later
# :Copyright: © 2017-2026 Lele Gaifax
#

from enum import IntEnum


class PgXmlStrictness(IntEnum):
    PG_XML_STRICTNESS_LEGACY = ...
    PG_XML_STRICTNESS_WELLFORMED = ...
    PG_XML_STRICTNESS_ALL = ...


class XmlBinaryType(IntEnum):
    XMLBINARY_BASE64 = ...
    XMLBINARY_HEX = ...


class XmlStandaloneType(IntEnum):
    XML_STANDALONE_YES = ...
    XML_STANDALONE_NO = ...
    XML_STANDALONE_NO_VALUE = ...
    XML_STANDALONE_OMITTED = ...
